departurerb/departure

- README.md
- lib/departure/connection_details.rb
- spec/departure/connection_details_spec.rb
This Fixes and issue that prevented the use of bash special characters in passwords.
> Escape bash in passwords

- CHANGELOG.md
- README.md
- lib/departure/connection_details.rb
- spec/departure/connection_details_spec.rb
Backport of https://github.com/departurerb/departure/pull/11 to Rails 4.2 version
> Allow use of bash special characters in passwords v4.2

- README.md
The Code Climate and Travis badges were still pointing to the redbooth organization, so I changed them.
> Update links of README badges

- CHANGELOG.md
- README.md
- lib/departure.rb
- spec/integration_spec.rb
Much of the use case for PERCONA_ARGS, at least as we use Departure and pt-osc, is to provide some performance tuning parameters to pt-osc. Departure should allow us to determine the safety of this ourselves.
> Permit user to determine safety of PERCONA_ARGS on migrate.

- departure_error.log
- lib/departure/command.rb
- spec/departure/command_spec.rb
There is no point 8 character blocks when combined with read_nonblock.
An 8k block will let Departure read whatever io pt-osc has available
all in one read operation.
> Increase the maximum size of a single read to a more reasonable value.

- departure_error.log
This file was being tracked by Git before we added it to .gitignore, so I'm removing it.
> Remove ignored departure_error.log file

- departure.gemspec
This removes actioncable, actionmailer, activejob and their dependencies.
Before:
```
~/src/departure[master] % wc -l Gemfile.lock
171 Gemfile.lock
```
After:
```
~/src/departure[master] % wc -l Gemfile.lock
131 Gemfile.lock
```
Extra: CI should be faster because it needs to download/install fewer dependencies.
> Depend only in railties and activerecord instead of full rails

- departure.gemspec
- lib/lhm/column_with_sql.rb
- spec/integration/columns_spec.rb
- spec/integration/data_migrations_spec.rb
- spec/integration/indexes_spec.rb
- spec/integration/references_spec.rb
- spec/integration/tables_spec.rb
- spec/integration_spec.rb
This adds support for Active Record 5.2.
There one small change in the main code, `ActiveRecord::Base.connection.lookup_cast_type` is now a private method and it is being used in the LHM compatibility layer.
All the other changes are in the specs, all the singleton methods from `ActiveRecord::Migrator` has been moved to instance methods inside of `ActiveRecord::MigrationContext` so we need to update all the specs using `Migrator`.
Props to @aqeelvn that did most of the work on this.
> Active Record 5.2 support

- CHANGELOG.md
- departure.gemspec
- lib/active_record/connection_adapters/percona_adapter.rb
- spec/fixtures/migrate/26_add_foreign_key.rb
- spec/fixtures/migrate/27_remove_foreign_key.rb
- spec/integration/foreign_keys_spec.rb
- spec/spec_helper.rb
- spec/support/matchers/have_foreign_key_on.rb
- test_database.rb
For `DROP FOREIGN KEY constraint_name` with pt-online-schema-change
requires specifying `_constraint_name` rather than the real
constraint_name. This is due to a limitation in MySQL:
pt-online-schema-change adds a leading underscore to foreign key
constraint names when creating the new table.
Additionally, this add specs to ensure that the addition and deletion
of foreign keys works correctly.
More details about this:
https://www.percona.com/blog/2017/03/21/dropping-foreign-key-constraint-using-pt-online-schema-change-2/
This closes https://github.com/departurerb/departure/issues/18
> Add proper support for Foreign Keys Removing.

- lib/active_record/connection_adapters/percona_adapter.rb
- spec/integration/foreign_keys_spec.rb
This fixes an error in the logic of the previous fix for foreign keys (f178ca2), the code was appending always a `_` before of foreign key name but looks like that is not how pt-online-schema-change works in all the cases.
According to pt-online-schema-change code (https://github.com/percona/percona-toolkit/blob/3.0/bin/pt-online-schema-change#L10841-L10854), is clear that `visit_DropForeignKey` should stop adding more `_` after of having two, the reason is that pt-online-schema-change drops all the `_` from the key name when copying to new table (e.g `products.__fk_name` is renamed to `_new_products.fk_name`)
Additionally, this add new specs to test the behavior of removal with multiple foreign key name patterns
> Fix bug removing foreign keys with double '__' as prefix

- README.md
While clicking through the readme I noticed that I was changing orgs so I fix0red it
> Point markdown links to newer repo

- .rubocop.yml
Small stuff. Rubocop warns about wrong scope for the `MultilineMethodCallIndentation` directive. Changed it to the correct scope.
> Fix rubocop wrong scope warning

- lib/departure.rb
- lib/departure/connection_base.rb
Fixes https://github.com/departurerb/departure/issues/31
> Prevent overriding default rails connection_specification_name ("primary")

- README.md
Hi, I was trying to set the --critical-load flag and realized the example had the syntax wrong.
> Fix PERCONA_ARGS syntax for critical-load option

- .travis.yml
- lib/departure/alter_argument.rb
- spec/departure/alter_argument_spec.rb
The previous regex required that the SQL generated include `'s around ids, which makes the parse fragile.  I changed the parse to look for any non-whitespace string after the ALTER TABLE.  This will support ALTER TABLE `foo` and ALTER TABLE foo , now.
I have also added an additional sub to the parsed_statement, for users utilizing strip_heredoc (has \n in the SQL) instead of squish (flattens the SQL), again, so this parser is less fragile.
> Regex changes to be less strict with syntax

- lib/departure/alter_argument.rb
- spec/departure/alter_argument_spec.rb
Because of quotes used for passing the command, if a default value for a column or a value for a column comment would include a double quote the quote would be stripped. The end result would be that the value would lose quotes and an incorrect comment or default value would be set.
This adds the double quote as one of the escapes.
> Make sure quotes in ALTER TABLE get correctly escaped

- departure.gemspec
It seems like departure has a strict `'>= 0.4.0', '<= 0.5.2'` mysql2 version lock since #35. 
This PR changes the requirement to allow version 0.5.3 since mysql2 0.5.3 has been [out since November 2019](https://rubygems.org/gems/mysql2/versions/0.5.3).
I tested this locally and the test case still passes, so I think this should be good to go.
> Relax mysql2 requirement to allow mysql2 0.5.3 gem

- .travis.yml
- departure.gemspec
- lib/active_record/connection_adapters/percona_adapter.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
- spec/integration/change_table_spec.rb
- spec/integration/columns_spec.rb
- spec/integration/data_migrations_spec.rb
- spec/integration/foreign_keys_spec.rb
- spec/integration/indexes_spec.rb
- spec/integration/references_spec.rb
- spec/integration/tables_spec.rb
- spec/integration_spec.rb
- spec/lhm_integration_spec.rb
- spec/spec_helper.rb
This PR includes a few changes to make departure works on Rails 6.0, and also updating build matrix to include all [currently maintained Ruby versions](https://www.ruby-lang.org/en/downloads/branches/) and testing against Rails 5.2 and Rails 6.
The fix for Rails 6 is actually just 85860c65ec676d079d44fabe1fbe905828de539f. However, I felt like it's necessary for us to make sure Departure still works on Rails 5.2, and so I updated gemspec and Travis so we'd run our spec against Rails 6.0 and Rails 5.2. I also took a liberty to remove Ruby 2.2 as it's already EOL and instead include [all versions of Rubies that currently being maintained](https://www.ruby-lang.org/en/downloads/branches/).
Note that one of the change that is necessary to get the spec passing is to change how we initialize …
> Add Rails 6 support

- README.md
The functionality to disable the non-blocking DDL is useful on certain migrations that don't need it. I added documentation for the `disable_departure!` method so is easier to find.
> Add documentation for disabling departure on particular migrations

- departure.gemspec
Hi,
I'm trying to use departure with the latest version of ActiveRecord (6.1.3.1) but the current dependency isn't allowing it. Would it be possible to relax it ?
Thanks 🙌
> Relax Rails dependency version

- departure.gemspec
This PR updates the upper bound of `RAILS_DEPENDENCY_VERSION` to allow Departure to run with Edge Rails, as Edge Rails is now targeting version 7.0: https://github.com/rails/rails/blob/1f566bd9ba0d1e657f09608b1d4140f9e11a8326/version.rb
Note that this will still block Departure to run with Rails 7.0.0 final when it comes out. Hence, we'll still have time to check the compatibility before saying that Departure works with Rails 7.0.0.
> Allow Departure to run against Edge Rails

- lib/active_record/connection_adapters/percona_adapter.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
In https://github.com/departurerb/departure/pull/58, there was an attempt to make this `remove_index` method works with Rails 6.1 by receiving and passing the second argument to `index_name_for_remove` method if this second argument is set.
However, this second `column_name` argument can still be nil when user try to invoke `remove_index` with compound index, for example:
remove_index :posts, column: %w(status user_id)
This commit fixes the issue by checking for Rails version first before calling `index_name_for_remove`.
Note that prior to this commit `master` branch is also broken after https://github.com/departurerb/departure/pull/58 was merged in, so this commit also fixing the test suite on both Rails 6.0 and 6.1.
> Fix problem with remove_index on Rails 6.1

- .gitignore
- lib/departure/command.rb
- lib/departure/configuration.rb
- lib/departure/runner.rb
- spec/departure/command_spec.rb
- spec/departure/runner_spec.rb
- spec/integration_spec.rb
We run `db:migrate` inside a Kubernetes job so for logging purposes it would be nice for everything that currently goes to `departure_error.log` (including debug logs if envvar PTDEBUG=1) to instead just go to STDOUT.
> Add configuration option to toggle stderr redirection

- spec/departure/command_spec.rb
This PR fixes a broken test in `master` branch:
```
Failures:
1) Departure::Command#run when not redirecting stderr executes the expected command
Failure/Error:
Open3.popen3(full_command) do |_stdin, stdout, _stderr, waith_thr|
begin
loop do
IO.select([stdout])
data = stdout.read_nonblock(8192)
logger.write_no_newline(data)
end
rescue EOFError # rubocop:disable Lint/HandleExceptions
ensure
Open3 received :popen3 with unexpected arguments
expected: ("pt-online-schema-change command")
got: ("pt-online-schema-change command 2>&1")
Please stub a default value first if message might be received with other args as well. 
```
I think this might have been introduced in https://github.com/departurerb/departure/pull/63. By default, if not redirecting `$stderr` to a file, we now redirect it to …
> Fix broken test in command_spec

- lib/active_record/connection_adapters/percona_adapter.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
- spec/integration/indexes_spec.rb
This PR fixes the problem that `add_index` no longer uses `pt-online-schema-change` to alter the table on Rails 6.1+.
This regression was unintentionally introduced back in #58 when an update was made to make Departure works with Rails 6.1. This did not get caught by our test suite because the test suite did not really test that the command was properly shelled out to `pt-online-schema-change` or not, and only asserting the result of the operation.
This commit updates the code in `add_index` to execute query with `ALTER TABLE` instead of `CREATE INDEX`. We need to call `execute` with a SQL starting with `ALTER TABLE` for Departure to kick in and shell out to `pt-online-schema-change`.
This commit also update specs related to adding/removing index to making sure that we actually call …
> Fix add_index on Rails 6.1

- lib/active_record/connection_adapters/for_alter.rb
- lib/active_record/connection_adapters/percona_adapter.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
- spec/integration/indexes_spec.rb
The first commit is a copy of #67. The other commits fix issues with bulk add_index and remove_index operations on Rails 6.1.
Tested on Rails 6.1.4.1
> Rails 6.1 fixes

- spec/departure/connection_details_spec.rb
- spec/integration/indexes_spec.rb
This PR contains two fixes:
It turns out that GitHub Actions set `PERCONA_DB_PASSWORD` to `root` (per investigation described [here](https://github.com/departurerb/departure/pull/74#issuecomment-1013090589)). We need this value to be nil so it'll pick up the password from `connection_data[:password]` instead.
Active Record will use `RENAME INDEX` command on MySQL version that supports `RENAME INDEX` command. Hence, we should assert for `RENAME INDEX` when `supports_rename_index?` is true. ([explaination](https://github.com/departurerb/departure/pull/74#issuecomment-1012026675))
---
Closes #74 as patches have been integrated here.
> Fix failing tests on master

- bin/console
- lib/active_record/connection_adapters/percona_adapter.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
- spec/fixtures/migrate/0030_data_migration_with_upsert_all.rb
- spec/integration/data_migrations_spec.rb
Rails 6 introduced [upsert_all](https://apidock.com/rails/v6.0.0/ActiveRecord/Persistence/ClassMethods/upsert_all) which delegates to `InsertAll` which ultimately calls `exec_query`. The MySQL upsert response is `nil` unlike postgres, so this PR accommodates for that response.
To reproduce:
- Run a migration that has any `upsert_all` call in it, it will error with `undefined method fields’ for nil:NilClass`
> fixes bug with upsert_all

- CHANGELOG.md
- config.yml.erb
- lib/departure/connection_details.rb
- spec/departure/connection_details_spec.rb
This PR adds `PERCONA_DB_SOCKET` environment variable support and configuration property `socket` that has higher priority than `host` and `port` configuration.
Tested on staging environments with proxysql socket connection.
Created by @Levii01
> Allow database connection via socket

- CHANGELOG.md
- lib/departure/dsn.rb
- spec/departure/dsn_spec.rb
As noted in [issue 86](https://github.com/departurerb/departure/issues/86), there is a bug in `pt-online-schema-change` where the `-P` option does not populate the port information for the general DSN which results in an "Use of uninitialized value" error.
This PR adds the ability to use "PERCONA_ADDED_DSN_ITEMS" environment variable to append items to the generated DSNs and, thereby, work around the existing bug with `pt-online-schema-change`.
> Allow custom additions to general DSN via environment variable

- CHANGELOG.md
- lib/active_record/connection_adapters/for_alter.rb
- spec/fixtures/migrate/0028_change_table.rb
Hi, in #62 it resolve a problem with `remove_index`, but the same problem is present in the `ForAlterStatements` module in the method `remove_index_for_alter`.
I simply added a `remove_index` in the integration test and using `RAILS_VERSION=6.0` make it failed.
> Fix problem remove_index_for_alter for Rails 6.0

- .github/workflows/test.yml
- .rubocop.yml
- CHANGELOG.md
- Dockerfile
- departure.gemspec
- lib/active_record/connection_adapters/percona_adapter.rb
- lib/lhm/column_with_sql.rb
- spec/active_record/connection_adapters/percona_adapter_spec.rb
- spec/integration/change_table_spec.rb
- spec/integration/columns_spec.rb
- spec/integration/data_migrations_spec.rb
- spec/integration/indexes_spec.rb
- spec/integration/tables_spec.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
Adds new methods to the Percona adapter required by a few changes in Rails 7.1:
* `raw_execute`:  https://github.com/rails/rails/pull/48061 reused the implementations from the MySQL2 adapter, but I can add any required customisations. 
* `internal_exec_query`: https://github.com/rails/rails/pull/48188 implementation from `exec_query`
* `reconnect`: I only added a stub because retries that way make less sense when offloading to PTOSC
On the tests front, I replaced `ActiveRecord::Migrator` with `ActiveRecord::MigrationContext` to solve method missing issues.
Gemspec/CI changes from https://github.com/departurerb/departure/pull/92
> Support Rails 7.1.2

- spec/spec_helper.rb
Some tests set up state which is used to initialize connections. If that initialization happens when the pool is populated, the pool will be poisoned with misconfigured connections, and the tests will fail.
Fixes #84.
> Drop DB connections between integration tests

- spec/lhm/adapter/add_column_spec.rb
- spec/lhm/adapter/change_column_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/column_definition_method.rb
Clears warnings when loading shared examples twice
> Avoid double definition of shared examples

- lib/departure/command.rb
- spec/departure/command_spec.rb
This is a follow up from: https://github.com/departurerb/departure/pull/63
If redirect_stderr = false then we shouldn't attempt to read an error message from departure_error.log since 1) it won't exist 2) we've been writing stderr to stdout the whole time anyway.
Fixes this error that prints if a migration fails:
```
rails aborted!
StandardError: An error has occurred, all later migrations canceled:
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/app/tmp/departure_error.log
```
> Don't try to read error message from file if we are writing to stderr 

- CHANGELOG.md
- README.md
- lib/departure/configuration.rb
- lib/departure/rails_adapter.rb
- lib/departure/rails_patches/active_record_migrator_with_advisory_lock_patch.rb
- spec/integration/change_table_spec.rb
- spec/integration/columns_spec.rb
- spec/integration/data_migrations_spec.rb
- spec/integration/indexes_spec.rb
- spec/integration/rails_adapter_spec.rb
- spec/integration/tables_spec.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
- spec/support/database_helpers.rb
*INFO* This PR builds on top of the `green-rails7.2` branch, you can compare the two [in this link](https://github.com/Austio/departure/compare/green-7.2..concurrent-migration-errors)
Prior to this change with departure, rails 7.1 and rails 7.2 would raise an `ActiveRecord::ConcurrentMigrationError` when running migrations *even* though the migrations successfully ran.  This migration error would also prevent `schema.rb` from being updated properly to reflect the current db schema after migration are ran.
This PR updates our rails adapter in verions 7.1 and 7.2 to ensure we don't raise an `ActiveRecord::ConcurrentMigrationError` when running migrations through patching `ActiveRecord::Migrator` to ensure we get and set an advisory lock with the same thread (see background below for more …
> Concurrent migration errors

- lib/active_record/connection_adapters/rails_8_1_departure_adapter.rb
- lib/departure/db_client.rb
- spec/departure/db_client_spec.rb
- spec/integration/foreign_keys_spec.rb
Moving RailsAdapter to be a very skinny wrapper around the existing database client. 
- Update adapter#new_client to initialize a Departure::DbClient and pass in the super'ed built new_client to delegate to
- Update Departure::DbClient to strictly pass alter statements to the percona command line, otherwise send to underlying client.  Expose query, alter_statement? and send_to_pt_online_schema_change methods
- Update adapter#query to delegate alter statements to send_to_pt_online_schema_change, otherwise super to the existing mysql2 adapter
> Remove Most non pt-online-schema-change logic from Departure
